version: "latest"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root

  python:
    image: python:3.11.7
    restart: no
    volumes:
      - .:/app  # Mount the entire current directory to /app in the container
    command: bash -c "pip install -r /app/requirements.txt && python /app/main.py && python /app/filtros.py"

volumes:
  postgres:

#QUITAR DATOS DE SALIDA SI DA ERROR